# Generated by Django 5.2.1 on 2025-05-10 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('policy_id', models.CharField(max_length=50)),
                ('authority_id', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarrierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('license_id', models.CharField(max_length=50)),
                ('authority_id', models.CharField(max_length=50)),
                ('equipment_type', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrier_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_city', models.CharField(max_length=200)),
                ('pickup_state', models.CharField(max_length=200)),
                ('delivery_city', models.CharField(max_length=200)),
                ('delivery_state', models.CharField(max_length=200)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('equipment_requirements', models.CharField(max_length=255)),
                ('pickup_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('commodity', models.CharField(max_length=255)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='main_app.brokerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('submitted_at', models.DateField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='main_app.carrierprofile')),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='main_app.load')),
            ],
        ),
    ]
