# Generated by Django 5.2.1 on 2025-05-15 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_offer_declined_reason_offer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='accepted',
        ),
    ]
